// Mixing numeric input with line-oriented string input can cause problems

#include <iostream>

int main()
{
    using namespace std;

    cout << "What year was your house built? \n";
    int year;
    cin >> year;
    // cin.get(); // run without this once and then run again without comment

    cout << "What is its street address? \n";
    char address[80];
    cin.getline(address, 80);

    cout << "Year built: " << year << endl;
    cout << "Address: " << address << endl;
    cout << "Done!\n";

    return 0;
}

// You never get the opportunity to enter the address.. if cin.get() is commented

/*
The problem is that when cin reads
the year, it leaves the newline generated by the Enter key in the input queue. Then cin.getline() reads the newline as an empty line and assigns a null string to the address array.


cin >> year;
cin.get(); // or cin.get(ch)

making above changes program runs properly
*/
